// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fzyxpkncrjpomfyffoyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6eXhwa25jcmpwb21meWZmb3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MjgzMzAsImV4cCI6MjA4OTAwNDMzMH0.DZvPTxQ5ZeSo5QMBUDiRpdFwSl0TpzPhl0x-eYInuaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);